import { MigrationInterface, QueryRunner } from "typeorm";

export class P6CreateProduitVariant1779994522621 implements MigrationInterface {
    name = 'P6CreateProduitVariant1779994522621'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE \`admin_activity_logs\` (\`id\` varchar(36) NOT NULL, \`action\` varchar(255) NOT NULL, \`entity\` varchar(255) NOT NULL, \`entityId\` varchar(255) NULL, \`payload\` json NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`admin_id\` varchar(36) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`produit_variants\` (\`id\` varchar(36) NOT NULL, \`sku\` varchar(255) NULL, \`options\` json NULL, \`price\` decimal(10,2) NOT NULL, \`price_eur\` decimal(10,2) NULL, \`compare_price\` decimal(10,2) NULL, \`stock\` int NOT NULL DEFAULT '0', \`is_active\` tinyint NOT NULL DEFAULT 1, \`sort_order\` int NOT NULL DEFAULT '0', \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`product_id\` varchar(36) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`ALTER TABLE \`order_items\` DROP COLUMN \`price\``);
        await queryRunner.query(`ALTER TABLE \`medias\` ADD \`position\` int NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`categories\` ADD \`image_url\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`categories\` ADD \`parent_id\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD \`shipping_address\` json NULL`);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD \`guest_email\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD \`invoice_url\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD \`payment_reference\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD UNIQUE INDEX \`IDX_0fd0d909c78f8efa1fb47d0c91\` (\`payment_reference\`)`);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD \`payment_method\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`order_items\` ADD \`unit_price\` decimal(12,2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`order_items\` ADD \`product_snapshot\` json NULL`);
        await queryRunner.query(`ALTER TABLE \`products\` ADD \`sku\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`products\` ADD \`brand\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`products\` ADD \`model\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`products\` ADD \`price_eur\` decimal(10,2) NULL`);
        await queryRunner.query(`ALTER TABLE \`products\` ADD \`status\` enum ('draft', 'active', 'archived') NOT NULL DEFAULT 'active'`);
        await queryRunner.query(`ALTER TABLE \`medias\` DROP FOREIGN KEY \`FK_9a3c9e824622cab3843bbfcc66f\``);
        await queryRunner.query(`ALTER TABLE \`medias\` DROP FOREIGN KEY \`FK_2ac39c7d3213e1297003d0bedcd\``);
        await queryRunner.query(`ALTER TABLE \`medias\` CHANGE \`alt\` \`alt\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`medias\` CHANGE \`product_id\` \`product_id\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`medias\` CHANGE \`category_id\` \`category_id\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`medias\` CHANGE \`deleted_at\` \`deleted_at\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`categories\` CHANGE \`description\` \`description\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`categories\` CHANGE \`deleted_at\` \`deleted_at\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`deliveries\` CHANGE \`tracking_number\` \`tracking_number\` varchar(100) NULL`);
        await queryRunner.query(`ALTER TABLE \`deliveries\` CHANGE \`carrier\` \`carrier\` varchar(100) NULL`);
        await queryRunner.query(`ALTER TABLE \`deliveries\` CHANGE \`notes\` \`notes\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`deliveries\` CHANGE \`shipped_at\` \`shipped_at\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`deliveries\` CHANGE \`delivered_at\` \`delivered_at\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`deliveries\` CHANGE \`deleted_at\` \`deleted_at\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP FOREIGN KEY \`FK_a922b820eeef29ac1c6800e826a\``);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP FOREIGN KEY \`FK_0dddcc76db9733e86e566e5e632\``);
        await queryRunner.query(`ALTER TABLE \`orders\` CHANGE \`status\` \`status\` enum ('pending', 'confirmed', 'processing', 'shipped', 'delivered', 'cancelled', 'refunded') NOT NULL COMMENT 'Current status of the order' DEFAULT 'pending'`);
        await queryRunner.query(`ALTER TABLE \`orders\` CHANGE \`total\` \`total\` decimal(12,2) NULL COMMENT 'Total order amount'`);
        await queryRunner.query(`ALTER TABLE \`orders\` CHANGE \`notes\` \`notes\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`orders\` CHANGE \`user_id\` \`user_id\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`orders\` CHANGE \`deleted_at\` \`deleted_at\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`orders\` CHANGE \`deliveryId\` \`deliveryId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`order_items\` CHANGE \`deleted_at\` \`deleted_at\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`products\` DROP FOREIGN KEY \`FK_54f60c73aa73cd760e06d9d2495\``);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`description\` \`description\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`stock\` \`stock\` decimal(12,2) NULL`);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`search_vector\` \`search_vector\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`categorie_id\` \`categorie_id\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`deleted_at\` \`deleted_at\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`carts_items\` CHANGE \`deleted_at\` \`deleted_at\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`carts\` DROP FOREIGN KEY \`FK_2ec1c94a977b940d85a4f498aea\``);
        await queryRunner.query(`ALTER TABLE \`carts\` CHANGE \`user_id\` \`user_id\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`carts\` CHANGE \`deleted_at\` \`deleted_at\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`phone\` \`phone\` varchar(20) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`password_reset_token\` \`password_reset_token\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`password_reset_expires\` \`password_reset_expires\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`deleted_at\` \`deleted_at\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`user_sessions\` CHANGE \`ip_address\` \`ip_address\` varchar(50) NULL`);
        await queryRunner.query(`ALTER TABLE \`user_sessions\` CHANGE \`user_agent\` \`user_agent\` varchar(500) NULL`);
        await queryRunner.query(`ALTER TABLE \`user_sessions\` CHANGE \`last_used_at\` \`last_used_at\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`medias\` ADD CONSTRAINT \`FK_9a3c9e824622cab3843bbfcc66f\` FOREIGN KEY (\`product_id\`) REFERENCES \`products\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`medias\` ADD CONSTRAINT \`FK_2ac39c7d3213e1297003d0bedcd\` FOREIGN KEY (\`category_id\`) REFERENCES \`categories\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`categories\` ADD CONSTRAINT \`FK_88cea2dc9c31951d06437879b40\` FOREIGN KEY (\`parent_id\`) REFERENCES \`categories\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD CONSTRAINT \`FK_a922b820eeef29ac1c6800e826a\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD CONSTRAINT \`FK_0dddcc76db9733e86e566e5e632\` FOREIGN KEY (\`deliveryId\`) REFERENCES \`deliveries\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`products\` ADD CONSTRAINT \`FK_54f60c73aa73cd760e06d9d2495\` FOREIGN KEY (\`categorie_id\`) REFERENCES \`categories\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`carts\` ADD CONSTRAINT \`FK_2ec1c94a977b940d85a4f498aea\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`admin_activity_logs\` ADD CONSTRAINT \`FK_f204d7cd01a6caa68157aea54f4\` FOREIGN KEY (\`admin_id\`) REFERENCES \`users\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`produit_variants\` ADD CONSTRAINT \`FK_ddb07a55509fbf6b860f59e68c3\` FOREIGN KEY (\`product_id\`) REFERENCES \`products\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`produit_variants\` DROP FOREIGN KEY \`FK_ddb07a55509fbf6b860f59e68c3\``);
        await queryRunner.query(`ALTER TABLE \`admin_activity_logs\` DROP FOREIGN KEY \`FK_f204d7cd01a6caa68157aea54f4\``);
        await queryRunner.query(`ALTER TABLE \`carts\` DROP FOREIGN KEY \`FK_2ec1c94a977b940d85a4f498aea\``);
        await queryRunner.query(`ALTER TABLE \`products\` DROP FOREIGN KEY \`FK_54f60c73aa73cd760e06d9d2495\``);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP FOREIGN KEY \`FK_0dddcc76db9733e86e566e5e632\``);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP FOREIGN KEY \`FK_a922b820eeef29ac1c6800e826a\``);
        await queryRunner.query(`ALTER TABLE \`categories\` DROP FOREIGN KEY \`FK_88cea2dc9c31951d06437879b40\``);
        await queryRunner.query(`ALTER TABLE \`medias\` DROP FOREIGN KEY \`FK_2ac39c7d3213e1297003d0bedcd\``);
        await queryRunner.query(`ALTER TABLE \`medias\` DROP FOREIGN KEY \`FK_9a3c9e824622cab3843bbfcc66f\``);
        await queryRunner.query(`ALTER TABLE \`user_sessions\` CHANGE \`last_used_at\` \`last_used_at\` datetime NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_sessions\` CHANGE \`user_agent\` \`user_agent\` varchar(500) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_sessions\` CHANGE \`ip_address\` \`ip_address\` varchar(50) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`deleted_at\` \`deleted_at\` datetime(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`password_reset_expires\` \`password_reset_expires\` datetime NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`password_reset_token\` \`password_reset_token\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`phone\` \`phone\` varchar(20) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`carts\` CHANGE \`deleted_at\` \`deleted_at\` datetime(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`carts\` CHANGE \`user_id\` \`user_id\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`carts\` ADD CONSTRAINT \`FK_2ec1c94a977b940d85a4f498aea\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`carts_items\` CHANGE \`deleted_at\` \`deleted_at\` datetime(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`deleted_at\` \`deleted_at\` datetime(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`categorie_id\` \`categorie_id\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`search_vector\` \`search_vector\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`stock\` \`stock\` decimal(12,2) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`description\` \`description\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`products\` ADD CONSTRAINT \`FK_54f60c73aa73cd760e06d9d2495\` FOREIGN KEY (\`categorie_id\`) REFERENCES \`categories\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`order_items\` CHANGE \`deleted_at\` \`deleted_at\` datetime(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`orders\` CHANGE \`deliveryId\` \`deliveryId\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`orders\` CHANGE \`deleted_at\` \`deleted_at\` datetime(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`orders\` CHANGE \`user_id\` \`user_id\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`orders\` CHANGE \`notes\` \`notes\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`orders\` CHANGE \`total\` \`total\` decimal(12,2) NULL COMMENT 'Total order amount' DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`orders\` CHANGE \`status\` \`status\` enum ('draft', 'pending', 'processing', 'shipped', 'delivered', 'cancelled', 'refunded') NOT NULL COMMENT 'Current status of the order' DEFAULT ''pending''`);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD CONSTRAINT \`FK_0dddcc76db9733e86e566e5e632\` FOREIGN KEY (\`deliveryId\`) REFERENCES \`deliveries\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD CONSTRAINT \`FK_a922b820eeef29ac1c6800e826a\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`deliveries\` CHANGE \`deleted_at\` \`deleted_at\` datetime(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`deliveries\` CHANGE \`delivered_at\` \`delivered_at\` datetime NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`deliveries\` CHANGE \`shipped_at\` \`shipped_at\` datetime NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`deliveries\` CHANGE \`notes\` \`notes\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`deliveries\` CHANGE \`carrier\` \`carrier\` varchar(100) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`deliveries\` CHANGE \`tracking_number\` \`tracking_number\` varchar(100) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`categories\` CHANGE \`deleted_at\` \`deleted_at\` datetime(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`categories\` CHANGE \`description\` \`description\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`medias\` CHANGE \`deleted_at\` \`deleted_at\` datetime(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`medias\` CHANGE \`category_id\` \`category_id\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`medias\` CHANGE \`product_id\` \`product_id\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`medias\` CHANGE \`alt\` \`alt\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`medias\` ADD CONSTRAINT \`FK_2ac39c7d3213e1297003d0bedcd\` FOREIGN KEY (\`category_id\`) REFERENCES \`categories\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`medias\` ADD CONSTRAINT \`FK_9a3c9e824622cab3843bbfcc66f\` FOREIGN KEY (\`product_id\`) REFERENCES \`products\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`products\` DROP COLUMN \`status\``);
        await queryRunner.query(`ALTER TABLE \`products\` DROP COLUMN \`price_eur\``);
        await queryRunner.query(`ALTER TABLE \`products\` DROP COLUMN \`model\``);
        await queryRunner.query(`ALTER TABLE \`products\` DROP COLUMN \`brand\``);
        await queryRunner.query(`ALTER TABLE \`products\` DROP COLUMN \`sku\``);
        await queryRunner.query(`ALTER TABLE \`order_items\` DROP COLUMN \`product_snapshot\``);
        await queryRunner.query(`ALTER TABLE \`order_items\` DROP COLUMN \`unit_price\``);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP COLUMN \`payment_method\``);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP INDEX \`IDX_0fd0d909c78f8efa1fb47d0c91\``);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP COLUMN \`payment_reference\``);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP COLUMN \`invoice_url\``);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP COLUMN \`guest_email\``);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP COLUMN \`shipping_address\``);
        await queryRunner.query(`ALTER TABLE \`categories\` DROP COLUMN \`parent_id\``);
        await queryRunner.query(`ALTER TABLE \`categories\` DROP COLUMN \`image_url\``);
        await queryRunner.query(`ALTER TABLE \`medias\` DROP COLUMN \`position\``);
        await queryRunner.query(`ALTER TABLE \`order_items\` ADD \`price\` decimal(12,2) NOT NULL`);
        await queryRunner.query(`DROP TABLE \`produit_variants\``);
        await queryRunner.query(`DROP TABLE \`admin_activity_logs\``);
    }

}
